name: My Mastodon Digest 
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
jobs:
  update:
    name: digest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@gh-action
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run digest
        run: |
          python run.py -n 24 -s ExtendedSimpleWeighted -t lax
      - name: publish
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: render
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
